### ISSUE TITLE
Query / feature request

### ISSUE THREAD

**Issue by nicholasgross** [evoluteur/d3-table-cards#1]
Hi Olivier - **love** this usage of D3.  Can you conceive of a way in which the cards could be grouped by a data point (into columns) and then sorted by some other data property?

i.e. Group by chakra, sorted by name;  would yield something like :

![image](https://user-images.githubusercontent.com/61851771/76032420-c87ea280-5f31-11ea-84ed-90eb2acb11a7.png)

Would be interested to hear your thoughts!

Many thanks,
Nick

**Comment by evoluteur** [comment]
Interesting idea. Here is what I would do:
1 - precompute the card order inside each chakra and store it in the new property of stones "cIdx".
Add the following at the end of data.js:
```javascript
var chakra = 0;
var counter = 0;
var maxCount = 0
data.forEach(function(stone){
  if(stone.chakra>chakra){
    chakra++;
    if(counter>maxCount){
      maxCount = counter
    }
    counter = 0;
  }
  stone.cIdx = counter++;
})
```
2 - In d3-table-cards.js, add a new "columns" layout which is the same as "cards" except for the "top" and "left" functions:
```javascript
columns: {
  top: function(d, i){return d.cIdx*94+'px'},
  left: function(d, i){return (d.chakra-1)*210+'px'},
  height: 84,
 ...
```
3 - In index.html, add a link to user the new layout:
<a href="javascript:redraw('columns')">Columns</a>
4 - Recalculate "totalHeight" using "maxCount".
That should work...

**Comment by nicholasgross** [comment]
That’s fantastic, Olivier - thanks for the direction. We’ll give that a go and let you know how it goes. 

cheers,
Nick
